name: effective_sales
description: Application for searching tickets as part of a test task in Effective Mobile

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State-manager  
  flutter_bloc: ^8.1.5

  # Navigation
  go_router: ^13.1.0

  # DI
  get_it: ^7.6.7
  injectable: ^2.3.5
  
  # Serialization 
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter

  # Networking
  retrofit: ^4.1.0
  shared_preferences: ^2.2.2
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  injectable_generator: ^2.4.2
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  retrofit_generator: '>=7.0.0 <8.0.0'

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/mock/offers/
    - assets/images/mock/arrival_recommendation/

  fonts:
    - family: EffectiveSalesIcons 
      fonts:
        - asset: assets/fonts/EffectiveSalesIcons.ttf
    
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Semibold.ttf
          weight: 600
        - asset: assets/fonts//SF-Pro-Display/SF-Pro-Display-Medium.ttf
          weight: 500