/// Flutter icons EffectiveSalesIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EffectiveSalesIcons
///      fonts:
///       - asset: fonts/EffectiveSalesIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EffectiveSalesIcons {
  EffectiveSalesIcons._();

  static const _kFontFam = 'EffectiveSalesIcons';
  static const String? _kFontPkg = null;

  static const IconData graphics = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flame = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hardWay = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rightarrow = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rectangle = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane2 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification2 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profileSmall = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotels = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shortReview = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification1 = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
